### ISSUE TITLE
1.14 Compatibility

### ISSUE THREAD

**Issue by hamcoremusic** [SBPrime/AsyncWorldEdit-Premium#175]
Just wondering if you will be supporting 1.14 once WorldEdit and WorldGuard get updated. Thanks!

**Comment by SBPrime** [comment]
**Short answer:** Of curse :)

**Long answer:**
1. Currently I support only beta builds of WE
2. You can get source for free (without the jar) on github
3, Compiled jar is available only for premium users
4. Compiled jar for free version is planned after WE reaches stable release (RC or Release not beta, but this might change)
5. Since 1.14 is out I'm going to support latest dev builds of WE (jar release, source - not decided)

**Comment by hamcoremusic** [comment]
Thank you for the timely reply! I am a Premium user anyway so this is very good news to see. It sucks when you spend money on a plugin then find out it's not supported anymore!

**Comment by SBPrime** [comment]
Done.
