### ISSUE TITLE
Ability to track Jobs

### ISSUE THREAD

**Issue by rlf** [SBPrime/AsyncWorldEdit-Premium#25]
Hi.

Even though we now have a "fine and dandy" API - unfortunately, it doesn't quite give us what we need.

In order to show any progress to a player, we need to be able to track progress for specific jobs.

With the current API, our options are limited to:
a) Add a progressDisplay to the ProgressDisplayManager (this ONLY works for sessions directly connected to a player, and these sessions seems to be merged if multiple jobs are queued at the same time, i.e. no way to deduce whether we are "clearing" or "creating" in the progressdisplay).
b) Add a timer-task, and query the block-queue on the BlockPlacer - Unfortunately, this also has the drawback, that we cannot know which job is currently "active", or how far a specific job has gone. This becomes even more murky, when using Console or UnknownPlayer as the same PlayerEntry for multiple other players.

Could you please expose some sort of query mechanism (or event listener), to listen to progress updates on specific Jobs?

I.e.

```
getAWE().getBlockPlacer().getJob(entry, index).getProgress()
```

or similar.

**Comment by SBPrime** [comment]
1. You need this for player tasks or for all tasks?
2. There are listeners for job added/state changed/removed (IBlockPlacer.addListener, removeListener)
3. Regarding the current number of blocks in a job (queued, the total can change since not all might be already queued), you can access them by using IBlockPlacer.getPlayerEvents(IPlayerEntry player); Then getQueue(), and filter out only entries that have the same job id that you are listening for.

**Comment by rlf** [comment]
1. All tasks (or more specifically, tasks for the UnknownPlayer).
2. The state-change won't give me progress, will it? Just a job-added/removed and Job-started/paused/finished.
3. Is each entry representing one block?

So what I need to do is this:

```
  create a paste-job for player A as UnknownPlayer
  start a timer-task, that queries IBlockPlacer
    iterate through all PlayerEvents on placer.getQueue() - and divide them into "jobId" buckets
    lookup JobEntry using the jobIds - and try to match the JobEntry with the paste-job
    report progress back to the user, esp. try to guess what the maxBlocks is (the highest values seen so far)?
    once no more events, stop the timer task
```

And this should ofc. be able to handle, another paste-job, or clear-job being started simultaneous, for either Player A, or another Player B.

Am I the only one thinking this might be able to be improved in the API?

**Comment by SBPrime** [comment]
Ad. 1. You should create your own (custom) player entry to filter out the jobs
Ad. 2. Exactly its only job added and state changed but that way you can add it to your own runner that checks the jobs progress
Ad. 3. Each entry is 1 operation. In most cases its 1 block, but for some operations its different (for example set data for whole chunk, spawn entity etc). 

Regarding the TODO, I would change 2 things: instead of using UnknownPlayer, use your own player, instead of dividing the entires you could simply count all entries for each job, something like SELECT count(1) GROUP BY jobId.

**"Am I the only one thinking this might be able to be improved in the API?"** Currently yes, because no one approached me regarding the API that’s why it has a low priority. I'll look into this, how to do it, but it wont be high on my todo list because there is a way to achieve what you need.

**Comment by rlf** [comment]
By saying "use your own player", do you mean make a custom "uSkyBlock Plugin Player Entry"? I wasn't aware that was an option.

Will look into that. That will definitely improve the chance of success - though currently I think we are sort of the only ones using UnknownPlayer, at least in my deployments.

**Comment by rlf** [comment]
Btw. an additional note, it's not "hard" to figure out how many blocks is left, as you stated, that can be done using the PlayerEvents queue. The problem is:
a) Identifying what jobId was actually assigned to the pastejob we created earlier
b) Identifying how many blocks the total "job" has (a percentage needs both) - and it seems the number of blocks changes over time (i.e. sometimes it will increase AFTER the job has started). Which  is why I simply assumed AWE would be better suited to answer those questions - than me trying to reverse-engineer and guess the state based on some vague hints from a rather fragmented suite of indications.

**Comment by SBPrime** [comment]
Ad 1. **The custom player entry** Thats exactly what I had in mind. Use the IPlayerManager.createPlayer(String name, UUID uuid); Then simply use it when executing IBlockPlacer.performAsAsyncJob. I don't remember but I think that there are 2-3 other plugins that use Console/Unknown player (I suggested changing to custom player, but I don't know if they did).

Ad 2. **Identifying what jobId...** Actually its fairly simple. You need to do 4 things:
1. Use a custom player
2. Use a identifiable jobName (for example UUID toString) while executing performAsAsyncJob
3. Listen for job added/removed and process only jobs that has your custom player, and the jobName is one of your names
4. Count all blocks for the job

Ad 3. **Identifying how many blocks the total "job" has**. Unfortunately AWE does not know how many blocks a job has in total. This is because AWE does not analyze the WE operation that its performing. It queues all the blocks that get added in stage 1 (calculation of changed blocks) and then in stage 2 places them. You can look at the open source version of AWE how it calculates the percentage for the progress bar and use something similar. 
https://github.com/SBPrime/AsyncWorldEdit/blob/master/AsyncWorldEdit/src/org/primesoft/asyncworldedit/blockPlacer/BlockPlacer.java#L893-L920

**Comment by SBPrime** [comment]
Any update?
