### ISSUE TITLE
WorldEdit crash //copy

### ISSUE THREAD

**Issue by andris155** [SBPrime/AsyncWorldEdit-Premium#29]
http://pastebin.com/mEVckYc6

**Comment by SBPrime** [comment]
Provide the AWE and server configuration.

**Comment by andris155** [comment]
Awe config: http://pastebin.com/iJKcJ6NE
Server: 7,5 GB RAM, HDD, Linux(Multicraft server controller), Intel Xenon E5

**Comment by SBPrime** [comment]
1. Your server crashed because it run out of memory "42. Caused by: java.lang.OutOfMemoryError: Java heap space"
2. Whats the free memory while the server is running?
3. How large was the copied area?
4. Was the crash instant or after a while?
5. Config looks ok
6. You need to remember that AWE has some out of memory detection, but it is only used for the block placer. Therefore if awe detected that its running out of memory it stopped all block queuing. Unfortunately only block SET operations are queued the block GET operations are not checked therefore not handled by AWE.

**Comment by andris155** [comment]
1. ok. :(
2. 500MB-3000MB
3. 500 000-600 000 blocks
4. //copy 1 minute later crash
5. Thanks
6. ok.

**Comment by SBPrime** [comment]
Well theres not much that I can help you with. You could consider looking at the "How many block can I queue" section on the [Wiki](https://github.com/SBPrime/AsyncWorldEdit-Premium/wiki). This is for the queue size but it should give you a rough estimate regarding the clipboard. You could try using the direct chunk commands (specially chunk clone) if you are copying one area of a map to another.
