### ISSUE TITLE
v3.2.3 config bug?

### ISSUE THREAD

**Issue by leasoncre** [SBPrime/AsyncWorldEdit-Premium#32]
i was trying to get the v12 config to generate with all the comments in it by:
1.deleteing the old config file (backed up first)
2. /awe reload config (or all)
3. open new config file
and found this: it had generated v11 config with comments. and doing a second awe reload erased the comments and updated the config to v12. (i didn't specifically check to the new config for the new settings though)

deleting the config file and restarting the server generated  the v12 config with no comments.

i was trying to find the 'disable awe for brushs' setting, i had assumed it was in the 'disabled operations' list. but without the commented settings i have no idea what they are.

**Comment by SBPrime** [comment]
I forgot to update the default config number and awe thinks that it's a old config that needs updating. Since its not a critical issue I'll fix it with the next release.

In the meantime you can open the awe jar using winrar/winzip/7z and extract the default config (change the version number inside the config so awe does not update it).

**Comment by leasoncre** [comment]
i'm not overly worried about it either. i just want to disable awe for brushes. thanks

**Comment by SBPrime** [comment]
Check here:
https://github.com/SBPrime/AsyncWorldEdit-Premium/wiki/Configuration

**Comment by SBPrime** [comment]
Done.
