### ISSUE TITLE
Holes

### ISSUE THREAD

**Issue by Kyle54106** [SBPrime/AsyncWorldEdit-Premium#34]
I'm getting the same problem like regular async where there are holes after queued block limit has been reached. Is there something in the configuration that I need to fix?

**Comment by SBPrime** [comment]
First of all did you do a server restart (not reload)? Is there anything on the console? What exactly causes the holes?

**Comment by Kyle54106** [comment]
I'm not sure what causes the holes, this is all that console says:

[12:55:20] [Server thread/INFO]: [AsyncWorldEdit] [GC] Free memory: 187MB, collecting...
[12:55:23] [Server thread/INFO]: [AsyncWorldEdit] [GC] ...time: 2659ms  free memory: 1540MB.

**Comment by SBPrime** [comment]
What command causes the problem? I checked this on my test server and when I'm running low on memory the operation is paused and AWE waits for the GC to free up some memory. 

The holes can appear only if you disable AWE (AWE toggle) or when you are running WE commands from a plugin that does it in a wrong way therefore the commands are executed from the main thread. If this happens AWE does not wait for the GC because that could cause the server to timeout.

**Comment by leasoncre** [comment]
is this related/similar-to the issue i've been having? [#23](https://github.com/SBPrime/AsyncWorldEdit-Premium/issues/23)

**Comment by SBPrime** [comment]
This issue was most likely caused by running commands on the server main thread and running out of ram. Since this was not reported since this issue, and there is no followup I'm closing the issue.
