### ISSUE TITLE
Using Inventory in WorldEdit - Blocks Not Giving / Taking for using world edit.

### ISSUE THREAD

**Issue by Fyrinlight** [SBPrime/AsyncWorldEdit-Premium#39]
With the beta of a new gamemode we're holding, we're giving people the ability to use a limited version of world edit, using the limiter found in ASync and having them use the blocks in their inventory, as per the use inventory setting in WorldEdit. We ran into some issues that exist when we are running async and not regular worldedit.

Issues:
- Blocks that you usually get for setting an area with air do not appear in your inventory unless you already had one of those blocks in your inventory. It does not go above one stack however.
- If you try to fill an area with a given block, you always end up with one left over, and it never goes away. Aka you can keep setting the block and it keeps putting one down but not removing it from your inventory.

Thanks for your time and loving this plugin!

Using ASync updated: March 1st.
WorldEdit version 6.1 Official bukkit release.

**Comment by Fyrinlight** [comment]
Hey, just wondering if you had a chance to look into this or if you need any additional information etc about this issue.

**Comment by SBPrime** [comment]
Not yet I spend all my time working on native support for 1.9 and this is a more complicated issue because I need to take into account BlocksHub integration. I still have some time before my next planed release I might be able to do something about it but no promises.

**Comment by SBPrime** [comment]
Ok I managed to find a fix for the problem. There is a downside: since WorldEdit assumes that everything is done in the server main thread id caches the player inventory BEFORE the command and then changes it AFTER the command is executed. 

Since all the operations in AWE are done in async thread the player can:
- have multiple operations running, 
- place and pick up blocks

That causes the approach in WE to be invalid. I can't store the changes made to the inventory because the player might not have the necessary blocks when the operation is done. Therefore I need to force update the player inventory each time a block is changed by WE. This leads to performance drop.
