### ISSUE TITLE
API not Updated

### ISSUE THREAD

**Issue by Maxetto** [SBPrime/AsyncWorldEdit-Premium#53]
From what I've been arguing with Island World's dev, It seems like the Premium API for this plugin is not updated to 3.3.X

Getting [THIS](http://pastebin.com/GNsxyfx3) error, while Island World is injecting fine into Premium AWE's API.
He also stated that the plugin was working fine till version 3.2.3.

Spigot 1.8.8
Island World 6.4
AsyncWorldEdit 3.3.0

**Comment by SBPrime** [comment]
First thing first the classes outside the api package should not be used externally by other plugins because they simply might change. There are not a part of Awe API.

Since version 3.3.0 I have hidden all the non api classes behind a special class loader and I obfuscated them.

The dev should have used the IAsyncEditSessionFactory he should never have used the AsyncEditSessionFactory.

If you like you can tell the dev to contact me directly.
